# Generated by Django 3.2.13 on 2022-06-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('fotoPerfil', models.ImageField(null=True, upload_to='fotosPerfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('nombreServicio', models.CharField(max_length=20, verbose_name='Tipo de servicio')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateTimeField(null=True)),
                ('comentario', models.CharField(max_length=50, verbose_name='Comentario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.perfil')),
            ],
        ),
    ]
