# Generated by Django 4.0.1 on 2022-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripción'),
        ),
    ]
