# Generated by Django 4.0.1 on 2022-05-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='IdCliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Cliente')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='nombreUsuario')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('telefono', models.IntegerField(max_length=50, verbose_name='telefono')),
                ('claveUsuario', models.CharField(max_length=50, verbose_name='claveUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idServicio')),
                ('tipoServicio', models.CharField(max_length=20, verbose_name='tipoServicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horas.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
