# Generated by Django 4.0.1 on 2022-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0002_cliente_servicio_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='claveUsuario',
            field=models.CharField(max_length=12, verbose_name='claveUsuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreUsuario',
            field=models.CharField(max_length=16, verbose_name='nombreUsuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(verbose_name='telefono'),
        ),
    ]
