# Generated by Django 4.0.1 on 2022-05-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0003_cliente_imagenusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateTimeField(null=True),
        ),
    ]
