# Generated by Django 4.0.1 on 2022-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0004_reserva_fechareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagenUsuario',
            field=models.ImageField(null=True, upload_to='ImagenUsuario'),
        ),
    ]
